---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

 "Just the place for a Snark!" the Bellman cried,  
   As he landed his crew with care;  
Supporting each man on the top of the tide
   By a finger entwined in his hair.  

"Just the place for a Snark! I have said it twice:  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Mary sat musing on the lamp-flame at the table  
Waiting for Warren. When she heard his step,  
She ran on tip-toe down the darkened passage  
To meet him in the doorway with the news  
And put him on his guard. ‘Silas is back.’  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

 The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Horton Hatches the Egg
	

I meant what I said  
And I said what I meant….  
An elephant’s faithful  
One hundred per cent!  

And it should be,  
it should be, it SHOULD be like that!  
Because Horton was faithful!  
He sat and he sat!  
	
“My goodness! My gracious!”  
they shouted. “MY WORD!  
It’s something brand new!  
IT’S AN ELEPHANT-BIRD!!”  
